spring:
 application:
  name: springcloud-guest
server:
 port: 8081
eureka:
 serviceUrl:
  defaultZone: http://localhost:8761/eureka/
springcloud-biz-repo:
 ribbon:
  connectTimeout: 3000
springcloud-biz-order:
 ribbon:
  connectTimeout: 4000